server:
  port: ${WELL_EATER_BACKEND_APP_PORT:8080}
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: INFO
spring:
  application:
    name: well-eater-backend
  datasource:
    url: jdbc:mysql://${WELL_EATER_DATABASE_HOST:localhost}:${WELL_EATER_DATABASE_PORT:3306}/${WELL_EATER_DATABASE:well_eater}
    username: ${WELL_EATER_DATABASE_USER:root}
    password: ${WELL_EATER_DATABASE_PASSWORD:rootroot}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  expiration-time: 43200000 # 12 hours in milliseconds
  public-key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEh+rjdJXaMWbLxGCAjCiyahNjRr72VQQeIUVKMGRbUpwATSr6zYxBQlkIWskdmFgRkvGNp89Z/zmKF6ncch7v6w
